### ISSUE TITLE
Autodeploy?

### ISSUE THREAD

**Issue by jonaskello** [autoapply/autoapply#29]
I'm currently evaluating weaveworks flux but I think I want a more lightweight solution and this seems like a nice tool! :-)

Flux has a function to watch a container registry and do a commit to the repo that upgrades the image. This is useful for continuous deployment, for example always updating a dev server to the latest image (where the image is called something like `master-{short_commit_sha}`). How would you handle the same thing with autoapply? It seems keel can do this job but since it does not update the yaml i the repo, I guess autoapply would overwrite what keel does so they would not work well together?

**Comment by pascalgn** [comment]
Yes, that's one of the reasons I wrote it, as the existing solutions were either too heavyweight or not flexible enough.

You're correct, it would not work well with keel: autoapply would run kubectl apply with the files in the git repository and keel would run kubectl apply with the updated image, both overwriting each other's changes.

What you can do is write a script which will check the registry for a new version of the image and then update the changes in the repository, something along the lines of this (not tested)

```bash
if docker pull "myregistry.io/image" | grep "Downloaded newer image"; then
  SHA=$(docker pull "myregistry.io/image" | grep Digest | cut -d ":" -f 3)
  sed -E "s|myregistry.io/image:.+|myregistry.io/image:${SHA}" app.yaml > app.yaml-new
  mv app.yaml-new app.yaml
  git commit -a -m "Updated myregistry.io/image to ${SHA}"
  git push
fi
```

**Comment by jonaskello** [comment]
I guess a tool that watches an image registry and commits image updates to the git repo would be a nice complement to autoapply. Something like keel but instead of patching the cluster it would commit the image tag changes to a git repo. One issue I think would be to know which file to commit changes to in the git repo. I'm not sure how flux manages this. Probably it adds some annotation that gives the path into the git repo?

Anyway, thanks for the info, I'll give this some more thought and see where I end up :-).
